import type { PredictionsState, Standing, ThirdPlaceStanding, ThirdPlaceQualification, KnockoutMatch } from '../shared/types'

export const predictions: PredictionsState = {
  A1: { home: 2, away: 1 },
  A2: { home: 0, away: 2 },
  A3: { home: 1, away: 0 },
  A4: { home: 1, away: 0 },
  A5: { home: 1, away: 1 },
  A6: { home: 1, away: 1 },

  B1: { home: 2, away: 0 },
  B2: { home: 0, away: 3 },
  B3: { home: 2, away: 0 },
  B4: { home: 3, away: 1 },
  B5: { home: 1, away: 0 },
  B6: { home: 1, away: 1 },

  C1: { home: 3, away: 0 },
  C2: { home: 0, away: 1 },
  C3: { home: 1, away: 1 },
  C4: { home: 4, away: 1 },
  C5: { home: 1, away: 2 },
  C6: { home: 2, away: 0 },

  D1: { home: 1, away: 0 },
  D2: { home: 0, away: 1 },
  D3: { home: 1, away: 0 },
  D4: { home: 1, away: 1 },
  D5: { home: 1, away: 2 },
  D6: { home: 2, away: 0 },

  E1: { home: 3, away: 0 },
  E2: { home: 2, away: 1 },
  E3: { home: 2, away: 0 },
  E4: { home: 3, away: 0 },
  E5: { home: 0, away: 3 },
  E6: { home: 0, away: 3 },

  F1: { home: 2, away: 0 },
  F2: { home: 2, away: 1 },
  F3: { home: 2, away: 1 },
  F4: { home: 1, away: 2 },
  F5: { home: 1, away: 1 },
  F6: { home: 1, away: 3 },

  G1: { home: 2, away: 0 },
  G2: { home: 1, away: 2 },
  G3: { home: 3, away: 0 },
  G4: { home: 0, away: 2 },
  G5: { home: 2, away: 0 },
  G6: { home: 0, away: 3 },

  H1: { home: 5, away: 0 },
  H2: { home: 1, away: 3 },
  H3: { home: 3, away: 0 },
  H4: { home: 3, away: 0 },
  H5: { home: 0, away: 2 },
  H6: { home: 0, away: 2 },

  I1: { home: 2, away: 0 },
  I2: { home: 0, away: 2 },
  I3: { home: 3, away: 0 },
  I4: { home: 1, away: 2 },
  I5: { home: 0, away: 2 },
  I6: { home: 2, away: 0 },

  J1: { home: 2, away: 0 },
  J2: { home: 3, away: 0 },
  J3: { home: 2, away: 0 },
  J4: { home: 1, away: 2 },
  J5: { home: 0, away: 2 },
  J6: { home: 0, away: 2 },

  K1: { home: 2, away: 0 },
  K2: { home: 0, away: 3 },
  K3: { home: 3, away: 0 },
  K4: { home: 2, away: 0 },
  K5: { home: 1, away: 2 },
  K6: { home: 2, away: 0 },

  L1: { home: 2, away: 0 },
  L2: { home: 2, away: 0 },
  L3: { home: 2, away: 0 },
  L4: { home: 0, away: 1 },
  L5: { home: 0, away: 3 },
  L6: { home: 2, away: 0 },

  '73': { home: 1, away: 0 },
  '74': { home: 2, away: 0 },
  '75': { home: 2, away: 0 },
  '76': { home: 2, away: 0 },
  '77': { home: 2, away: 0 },
  '78': { home: 1, away: 1, drawWinner: 'home' },
  '79': { home: 2, away: 1 },
  '80': { home: 3, away: 0 },
  '81': { home: 2, away: 0 },
  '82': { home: 2, away: 0 },
  '83': { home: 1, away: 0 },
  '84': { home: 2, away: 0 },
  '85': { home: 1, away: 1, drawWinner: 'home' },
  '86': { home: 3, away: 1 },
  '87': { home: 2, away: 1 },
  '88': { home: 1, away: 0 },
  '89': { home: 0, away: 2 },
  '90': { home: 0, away: 2 },
  '91': { home: 2, away: 0 },
  '92': { home: 0, away: 2 },
  '93': { home: 0, away: 2 },
  '94': { home: 1, away: 1, drawWinner: 'away' },
  '95': { home: 2, away: 0 },
  '96': { home: 1, away: 2 },
  '97': { home: 2, away: 1 },
  '98': { home: 2, away: 1 },
  '99': { home: 2, away: 1 },
  '100': { home: 2, away: 1 },
  '101': { home: 2, away: 1 },
  '102': { home: 2, away: 1 },
  '103': { home: 1, away: 0 },
  '104': { home: 1, away: 1, drawWinner: 'away' },
}

export const topGoalscorer = 'קיליאן אמפבה '
export const label = 'אלדד לוי'

export const groupTables: Record<string, Standing[]> = {
  A: [
    { team: 'Czech Republic', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 1, points: 7 },
    { team: 'Mexico', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 2, points: 7 },
    { team: 'South Africa', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 1 },
    { team: 'South Korea', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 1, goalsAgainst: 4, points: 1 },
  ],
  B: [
    { team: 'Switzerland', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 6, goalsAgainst: 0, points: 9 },
    { team: 'Canada', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 5, goalsAgainst: 2, points: 6 },
    { team: 'Bosnia and Herzegovina', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 1, goalsAgainst: 5, points: 1 },
    { team: 'Qatar', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 2, goalsAgainst: 7, points: 1 },
  ],
  C: [
    { team: 'Brazil', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 9, goalsAgainst: 2, points: 9 },
    { team: 'Scotland', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4 },
    { team: 'Morocco', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4 },
    { team: 'Haiti', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 7, points: 0 },
  ],
  D: [
    { team: 'United States', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 4, goalsAgainst: 1, points: 9 },
    { team: 'Paraguay', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 2, points: 4 },
    { team: 'Turkey', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4 },
    { team: 'Australia', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 4, points: 0 },
  ],
  E: [
    { team: 'Germany', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 8, goalsAgainst: 0, points: 9 },
    { team: 'Ivory Coast', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 5, goalsAgainst: 3, points: 6 },
    { team: 'Ecuador', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 4, goalsAgainst: 5, points: 3 },
    { team: 'Curaçao', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 9, points: 0 },
  ],
  F: [
    { team: 'Netherlands', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 7, goalsAgainst: 2, points: 9 },
    { team: 'Sweden', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 4, goalsAgainst: 4, points: 4 },
    { team: 'Japan', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4 },
    { team: 'Tunisia', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 3, goalsAgainst: 7, points: 0 },
  ],
  G: [
    { team: 'Belgium', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 8, goalsAgainst: 0, points: 9 },
    { team: 'Egypt', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 4, goalsAgainst: 2, points: 6 },
    { team: 'New Zealand', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 6, points: 3 },
    { team: 'Iran', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 7, points: 0 },
  ],
  H: [
    { team: 'Spain', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 10, goalsAgainst: 0, points: 9 },
    { team: 'Uruguay', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 6, goalsAgainst: 3, points: 6 },
    { team: 'Saudi Arabia', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 6, points: 3 },
    { team: 'Cape Verde', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 10, points: 0 },
  ],
  I: [
    { team: 'France', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 7, goalsAgainst: 0, points: 9 },
    { team: 'Senegal', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 4, goalsAgainst: 3, points: 6 },
    { team: 'Norway', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 4, points: 3 },
    { team: 'Iraq', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 7, points: 0 },
  ],
  J: [
    { team: 'Argentina', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 6, goalsAgainst: 0, points: 9 },
    { team: 'Austria', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 5, goalsAgainst: 2, points: 6 },
    { team: 'Algeria', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 5, points: 3 },
    { team: 'Jordan', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 7, points: 0 },
  ],
  K: [
    { team: 'Portugal', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 7, goalsAgainst: 1, points: 9 },
    { team: 'Colombia', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 6, goalsAgainst: 2, points: 6 },
    { team: 'DR Congo', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3 },
    { team: 'Uzbekistan', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 8, points: 0 },
  ],
  L: [
    { team: 'England', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 7, goalsAgainst: 0, points: 9 },
    { team: 'Croatia', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 2, points: 6 },
    { team: 'Ghana', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3 },
    { team: 'Panama', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 6, points: 0 },
  ],
}

export const thirdPlaceTeams: ThirdPlaceStanding[] = [
    { team: 'South Africa', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 1, group: 'A' },
    { team: 'Bosnia and Herzegovina', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 1, goalsAgainst: 5, points: 1, group: 'B' },
    { team: 'Morocco', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4, group: 'C' },
    { team: 'Turkey', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4, group: 'D' },
    { team: 'Ecuador', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 4, goalsAgainst: 5, points: 3, group: 'E' },
    { team: 'Japan', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4, group: 'F' },
    { team: 'New Zealand', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 6, points: 3, group: 'G' },
    { team: 'Saudi Arabia', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 6, points: 3, group: 'H' },
    { team: 'Norway', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 4, points: 3, group: 'I' },
    { team: 'Algeria', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 5, points: 3, group: 'J' },
    { team: 'DR Congo', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3, group: 'K' },
    { team: 'Ghana', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3, group: 'L' },
]

export const thirdPlaceQualification: ThirdPlaceQualification = {
  resolved: true,
  all: [
    { team: 'Turkey', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4, group: 'D' },
    { team: 'Morocco', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4, group: 'C' },
    { team: 'Japan', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4, group: 'F' },
    { team: 'Ecuador', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 4, goalsAgainst: 5, points: 3, group: 'E' },
    { team: 'Norway', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 4, points: 3, group: 'I' },
    { team: 'DR Congo', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3, group: 'K' },
    { team: 'Ghana', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3, group: 'L' },
    { team: 'Saudi Arabia', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 6, points: 3, group: 'H' },
    { team: 'Algeria', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 5, points: 3, group: 'J' },
    { team: 'New Zealand', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 6, points: 3, group: 'G' },
    { team: 'South Africa', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 1, group: 'A' },
    { team: 'Bosnia and Herzegovina', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 1, goalsAgainst: 5, points: 1, group: 'B' },
  ],
  qualifiers: [
    { team: 'Turkey', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4, group: 'D' },
    { team: 'Morocco', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4, group: 'C' },
    { team: 'Japan', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 4, points: 4, group: 'F' },
    { team: 'Ecuador', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 4, goalsAgainst: 5, points: 3, group: 'E' },
    { team: 'Norway', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 4, points: 3, group: 'I' },
    { team: 'DR Congo', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3, group: 'K' },
    { team: 'Ghana', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 3, group: 'L' },
    { team: 'Saudi Arabia', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 6, points: 3, group: 'H' },
  ],
}

export const knockoutBracket: KnockoutMatch[] = [
  { matchNum: 73, home: 'Mexico', away: 'Canada', resolved: true, scores: { home: 1, away: 0 }, matchDate: '28 ביוני', kickoffIST: '22:00' },
  { matchNum: 74, home: 'Germany', away: 'Turkey', resolved: true, scores: { home: 2, away: 0 }, matchDate: '29 ביוני', kickoffIST: '23:30' },
  { matchNum: 75, home: 'Netherlands', away: 'Scotland', resolved: true, scores: { home: 2, away: 0 }, matchDate: '30 ביוני', kickoffIST: '04:00' },
  { matchNum: 76, home: 'Brazil', away: 'Sweden', resolved: true, scores: { home: 2, away: 0 }, matchDate: '29 ביוני', kickoffIST: '20:00' },
  { matchNum: 77, home: 'France', away: 'Japan', resolved: true, scores: { home: 2, away: 0 }, matchDate: '1 ביולי', kickoffIST: '00:00' },
  { matchNum: 78, home: 'Ivory Coast', away: 'Senegal', resolved: true, scores: { home: 1, away: 1, drawWinner: 'home' }, matchDate: '30 ביוני', kickoffIST: '20:00' },
  { matchNum: 79, home: 'Czech Republic', away: 'Morocco', resolved: true, scores: { home: 2, away: 1 }, matchDate: '1 ביולי', kickoffIST: '04:00' },
  { matchNum: 80, home: 'England', away: 'DR Congo', resolved: true, scores: { home: 3, away: 0 }, matchDate: '1 ביולי', kickoffIST: '19:00' },
  { matchNum: 81, home: 'United States', away: 'Norway', resolved: true, scores: { home: 2, away: 0 }, matchDate: '2 ביולי', kickoffIST: '03:00' },
  { matchNum: 82, home: 'Belgium', away: 'Saudi Arabia', resolved: true, scores: { home: 2, away: 0 }, matchDate: '1 ביולי', kickoffIST: '23:00' },
  { matchNum: 83, home: 'Colombia', away: 'Croatia', resolved: true, scores: { home: 1, away: 0 }, matchDate: '3 ביולי', kickoffIST: '02:00' },
  { matchNum: 84, home: 'Spain', away: 'Austria', resolved: true, scores: { home: 2, away: 0 }, matchDate: '2 ביולי', kickoffIST: '22:00' },
  { matchNum: 85, home: 'Switzerland', away: 'Ecuador', resolved: true, scores: { home: 1, away: 1, drawWinner: 'home' }, matchDate: '3 ביולי', kickoffIST: '06:00' },
  { matchNum: 86, home: 'Argentina', away: 'Uruguay', resolved: true, scores: { home: 3, away: 1 }, matchDate: '4 ביולי', kickoffIST: '01:00' },
  { matchNum: 87, home: 'Portugal', away: 'Ghana', resolved: true, scores: { home: 2, away: 1 }, matchDate: '4 ביולי', kickoffIST: '04:30' },
  { matchNum: 88, home: 'Paraguay', away: 'Egypt', resolved: true, scores: { home: 1, away: 0 }, matchDate: '3 ביולי', kickoffIST: '21:00' },
  { matchNum: 89, home: 'Germany', away: 'France', resolved: true, scores: { home: 0, away: 2 }, matchDate: '5 ביולי', kickoffIST: '00:00' },
  { matchNum: 90, home: 'Mexico', away: 'Netherlands', resolved: true, scores: { home: 0, away: 2 }, matchDate: '4 ביולי', kickoffIST: '20:00' },
  { matchNum: 91, home: 'Brazil', away: 'Ivory Coast', resolved: true, scores: { home: 2, away: 0 }, matchDate: '5 ביולי', kickoffIST: '23:00' },
  { matchNum: 92, home: 'Czech Republic', away: 'England', resolved: true, scores: { home: 0, away: 2 }, matchDate: '6 ביולי', kickoffIST: '03:00' },
  { matchNum: 93, home: 'Colombia', away: 'Spain', resolved: true, scores: { home: 0, away: 2 }, matchDate: '6 ביולי', kickoffIST: '22:00' },
  { matchNum: 94, home: 'United States', away: 'Belgium', resolved: true, scores: { home: 1, away: 1, drawWinner: 'away' }, matchDate: '7 ביולי', kickoffIST: '03:00' },
  { matchNum: 95, home: 'Argentina', away: 'Paraguay', resolved: true, scores: { home: 2, away: 0 }, matchDate: '7 ביולי', kickoffIST: '19:00' },
  { matchNum: 96, home: 'Switzerland', away: 'Portugal', resolved: true, scores: { home: 1, away: 2 }, matchDate: '7 ביולי', kickoffIST: '23:00' },
  { matchNum: 97, home: 'France', away: 'Netherlands', resolved: true, scores: { home: 2, away: 1 }, matchDate: '9 ביולי', kickoffIST: '23:00' },
  { matchNum: 98, home: 'Spain', away: 'Belgium', resolved: true, scores: { home: 2, away: 1 }, matchDate: '10 ביולי', kickoffIST: '22:00' },
  { matchNum: 99, home: 'Brazil', away: 'England', resolved: true, scores: { home: 2, away: 1 }, matchDate: '12 ביולי', kickoffIST: '00:00' },
  { matchNum: 100, home: 'Argentina', away: 'Portugal', resolved: true, scores: { home: 2, away: 1 }, matchDate: '12 ביולי', kickoffIST: '04:00' },
  { matchNum: 101, home: 'France', away: 'Spain', resolved: true, scores: { home: 2, away: 1 }, matchDate: '14 ביולי', kickoffIST: '22:00' },
  { matchNum: 102, home: 'Brazil', away: 'Argentina', resolved: true, scores: { home: 2, away: 1 }, matchDate: '15 ביולי', kickoffIST: '22:00' },
  { matchNum: 103, home: 'Spain', away: 'Argentina', resolved: true, scores: { home: 1, away: 0 }, matchDate: '19 ביולי', kickoffIST: '00:00' },
  { matchNum: 104, home: 'France', away: 'Brazil', resolved: true, scores: { home: 1, away: 1, drawWinner: 'away' }, matchDate: '19 ביולי', kickoffIST: '22:00' },
]

export const predictedChampion = 'Brazil'
export const predictedThirdPlaceWinner = 'Spain'
