import type { PredictionsState, Standing } from '../shared/types'

export const predictions: PredictionsState = {
  A1: { home: 2, away: 0 },
  A2: { home: 1, away: 1 },
  A3: { home: 1, away: 1 },
  A4: { home: 1, away: 0 },
  A5: { home: 1, away: 1 },
  A6: { home: 0, away: 1 },

  B1: { home: 1, away: 0 },
  B2: { home: 0, away: 2 },
  B3: { home: 1, away: 0 },
  B4: { home: 1, away: 0 },
  B5: { home: 0, away: 0 },
  B6: { home: 2, away: 0 },

  C1: { home: 1, away: 0 },
  C2: { home: 0, away: 2 },
  C3: { home: 1, away: 2 },
  C4: { home: 3, away: 0 },
  C5: { home: 0, away: 1 },
  C6: { home: 3, away: 0 },

  D1: { home: 1, away: 0 },
  D2: { home: 0, away: 1 },
  D3: { home: 1, away: 0 },
  D4: { home: 0, away: 0 },
  D5: { home: 0, away: 0 },
  D6: { home: 0, away: 1 },

  E1: { home: 3, away: 0 },
  E2: { home: 1, away: 1 },
  E3: { home: 1, away: 0 },
  E4: { home: 2, away: 1 },
  E5: { home: 0, away: 3 },
  E6: { home: 1, away: 2 },

  F1: { home: 1, away: 0 },
  F2: { home: 1, away: 0 },
  F3: { home: 1, away: 0 },
  F4: { home: 1, away: 2 },
  F5: { home: 0, away: 0 },
  F6: { home: 1, away: 1 },

  G1: { home: 1, away: 1 },
  G2: { home: 1, away: 0 },
  G3: { home: 2, away: 1 },
  G4: { home: 1, away: 2 },
  G5: { home: 1, away: 1 },
  G6: { home: 0, away: 1 },

  H1: { home: 3, away: 0 },
  H2: { home: 0, away: 1 },
  H3: { home: 1, away: 0 },
  H4: { home: 2, away: 0 },
  H5: { home: 1, away: 2 },
  H6: { home: 1, away: 1 },

  I1: { home: 1, away: 0 },
  I2: { home: 0, away: 1 },
  I3: { home: 3, away: 0 },
  I4: { home: 0, away: 0 },
  I5: { home: 0, away: 0 },
  I6: { home: 2, away: 1 },

  J1: { home: 1, away: 1 },
  J2: { home: 2, away: 0 },
  J3: { home: 0, away: 0 },
  J4: { home: 0, away: 1 },
  J5: { home: 0, away: 0 },
  J6: { home: 0, away: 3 },

  K1: { home: 1, away: 0 },
  K2: { home: 0, away: 2 },
  K3: { home: 3, away: 0 },
  K4: { home: 0, away: 0 },
  K5: { home: 1, away: 1 },
  K6: { home: 1, away: 1 },

  L1: { home: 0, away: 0 },
  L2: { home: 2, away: 1 },
  L3: { home: 1, away: 0 },
  L4: { home: 0, away: 2 },
  L5: { home: 0, away: 3 },
  L6: { home: 1, away: 1 },

  '73': { home: 1, away: 0 },
  '74': { home: 1, away: 0 },
  '75': { home: 0, away: 1 },
  '76': { home: 1, away: 0 },
  '77': { home: 1, away: 0 },
  '78': { home: 0, away: 0, drawWinner: 'away' },
  '79': { home: 1, away: 1, drawWinner: 'home' },
  '80': { home: 1, away: 0 },
  '81': { home: 1, away: 0 },
  '82': { home: 0, away: 1 },
  '83': { home: 1, away: 0 },
  '84': { home: 2, away: 0 },
  '85': { home: 1, away: 0 },
  '86': { home: 1, away: 0 },
  '87': { home: 1, away: 0 },
  '88': { home: 0, away: 1 },
  '89': { home: 0, away: 1 },
  '90': { home: 0, away: 1 },
  '91': { home: 2, away: 1 },
  '92': { home: 1, away: 2 },
  '93': { home: 0, away: 2 },
  '94': { home: 1, away: 0 },
  '95': { home: 2, away: 0 },
  '96': { home: 1, away: 2 },
  '97': { home: 1, away: 0 },
  '98': { home: 2, away: 0 },
  '99': { home: 2, away: 1 },
  '100': { home: 1, away: 0 },
  '101': { home: 1, away: 0 },
  '102': { home: 2, away: 1 },
  '103': { home: 0, away: 1 },
  '104': { home: 2, away: 1 },
}

export const topGoalscorer = 'קיליאן אמבפה'
export const label = 'עידן מלמד'

export const groupTables: Record<string, Standing[]> = {
  A: [
    { team: 'Mexico', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 1, points: 7 },
    { team: 'South Korea', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 2, goalsAgainst: 2, points: 4 },
    { team: 'Czech Republic', played: 3, won: 0, drawn: 3, lost: 0, goalsFor: 3, goalsAgainst: 3, points: 3 },
    { team: 'South Africa', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 1, goalsAgainst: 4, points: 1 },
  ],
  B: [
    { team: 'Switzerland', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 3, goalsAgainst: 0, points: 7 },
    { team: 'Canada', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 2, goalsAgainst: 0, points: 7 },
    { team: 'Bosnia and Herzegovina', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 2, points: 3 },
    { team: 'Qatar', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 5, points: 0 },
  ],
  C: [
    { team: 'Brazil', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 5, goalsAgainst: 0, points: 9 },
    { team: 'Morocco', played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 5, goalsAgainst: 2, points: 6 },
    { team: 'Scotland', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 3, points: 3 },
    { team: 'Haiti', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 8, points: 0 },
  ],
  D: [
    { team: 'United States', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 2, goalsAgainst: 0, points: 7 },
    { team: 'Turkey', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 1, goalsAgainst: 0, points: 5 },
    { team: 'Australia', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 1, goalsAgainst: 2, points: 3 },
    { team: 'Paraguay', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 0, goalsAgainst: 2, points: 1 },
  ],
  E: [
    { team: 'Germany', played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 6, goalsAgainst: 1, points: 9 },
    { team: 'Ivory Coast', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 4, goalsAgainst: 2, points: 4 },
    { team: 'Ecuador', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 4, goalsAgainst: 4, points: 4 },
    { team: 'Curaçao', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 8, points: 0 },
  ],
  F: [
    { team: 'Netherlands', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 3, goalsAgainst: 1, points: 7 },
    { team: 'Japan', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 2, goalsAgainst: 2, points: 4 },
    { team: 'Sweden', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 1, goalsAgainst: 1, points: 4 },
    { team: 'Tunisia', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 2, goalsAgainst: 4, points: 1 },
  ],
  G: [
    { team: 'Belgium', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 2, points: 7 },
    { team: 'Egypt', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 4, goalsAgainst: 3, points: 5 },
    { team: 'Iran', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4 },
    { team: 'New Zealand', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 4, points: 0 },
  ],
  H: [
    { team: 'Spain', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 5, goalsAgainst: 1, points: 7 },
    { team: 'Uruguay', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 1, points: 7 },
    { team: 'Saudi Arabia', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 2, goalsAgainst: 3, points: 3 },
    { team: 'Cape Verde', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 7, points: 0 },
  ],
  I: [
    { team: 'France', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 0, points: 7 },
    { team: 'Norway', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 1, goalsAgainst: 0, points: 5 },
    { team: 'Senegal', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 2, goalsAgainst: 2, points: 4 },
    { team: 'Iraq', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 6, points: 0 },
  ],
  J: [
    { team: 'Argentina', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 4, goalsAgainst: 1, points: 5 },
    { team: 'Algeria', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 2, goalsAgainst: 1, points: 5 },
    { team: 'Austria', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 2, goalsAgainst: 0, points: 5 },
    { team: 'Jordan', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 6, points: 0 },
  ],
  K: [
    { team: 'Portugal', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 5, goalsAgainst: 1, points: 7 },
    { team: 'Colombia', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 3, goalsAgainst: 1, points: 5 },
    { team: 'DR Congo', played: 3, won: 0, drawn: 2, lost: 1, goalsFor: 1, goalsAgainst: 2, points: 2 },
    { team: 'Uzbekistan', played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 1, goalsAgainst: 6, points: 1 },
  ],
  L: [
    { team: 'England', played: 3, won: 2, drawn: 1, lost: 0, goalsFor: 4, goalsAgainst: 0, points: 7 },
    { team: 'Croatia', played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 3, goalsAgainst: 1, points: 5 },
    { team: 'Ghana', played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 3, points: 4 },
    { team: 'Panama', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 7, points: 0 },
  ],
}
